name: Build Mequal and Push to Quay

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  mequal-deploy:
    runs-on: ubuntu-latest
    environment: mequal
    steps:
      - uses: actions/checkout@v4

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.QUAY_REPO }}:${{ github.sha }} -t ${{ secrets.QUAY_REPO }}:latest ./container_files/Containerfile

      - name: Push to Quay
        run: docker push ${{ secrets.QUAY_REPO }} --all-tags
